setup.sh: check that temp file was created successfully, call rm command instead of potential alias (fix #343)

diff --git a/cmake/templates/setup.sh.in b/cmake/templates/setup.sh.in
--- a/cmake/templates/setup.sh.in
+++ b/cmake/templates/setup.sh.in
@@ -36,9 +36,14 @@ export PYTHONPATH
 # invoke Python script to generate necessary exports of environment variables
 _MKTEMP=`which mktemp`
 _SETUP_TMP=`$_MKTEMP /tmp/setup.sh.XXXXXXXXXX`
+if [ $? -ne 0 -o ! -f "$_SETUP_TMP" ]; then
+  echo "Could not create temporary file: $_SETUP_TMP"
+  return 1
+fi
 $_SETUP_UTIL $@ > $_SETUP_TMP
 . $_SETUP_TMP
-rm $_SETUP_TMP
+_RM=`which rm`
+$_RM $_SETUP_TMP
 
 # remember type of shell if not already set
 if [ -z "$CATKIN_SHELL" ]; then
